version: '2.3'
services:
  dev_api:
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /usr/src/app
    restart: unless-stopped
    environment:
      NODE_ENV: "development"
      PORT: 8080
    volumes:
      - ..:/usr/local/src
      - /usr/local/src/node_modules
    tty: true
    ports:
      - 8080:8080
    command: /bin/sh -c "npm run start:server:prod"
